/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rakesh' at '10/19/16 9:53 PM' with Gradle 3.1
 *
 * @author rakesh, @date 10/19/16 9:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
